### ISSUE TITLE
There is an error in converter.py

### ISSUE THREAD

**Issue by Supergamer5465** [Nya0/recaptcha-v2-bypass#4]
Currently in converter.py, line 6 says this:
```
sound.export(os.path.expanduser("~/Downloads/audio.wav", format="wav")) 
```
However, there is one parenthesis typed wrongly. It should be this:
```
sound.export(os.path.expanduser("~/Downloads/audio.wav"), format="wav") 
```
Otherwise, it will say "Unexpected keyword argument 'format' in function call"

**Comment by Nya0** [comment]
It should work without doing that
